//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.19 at 06:15:44 PM CEST 
//


package com.a9.opensearch._11;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for OpenSearchDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpenSearchDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}ShortName"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Description"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Tags" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Contact" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Url" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}LongName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Image" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Query" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Developer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Attribution" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}SyndicationRight" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}AdultContent" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}Language" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}OutputEncoding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://a9.com/-/spec/opensearch/1.1/}InputEncoding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpenSearchDescription", propOrder = {
    "shortName",
    "description",
    "tags",
    "contact",
    "urls",
    "longName",
    "images",
    "queries",
    "developer",
    "attribution",
    "syndicationRight",
    "adultContent",
    "languages",
    "outputEncodings",
    "inputEncodings"
})
@XmlRootElement(name = "OpenSearchDescription")
public class OpenSearchDescription {

    @XmlElement(name = "ShortName", required = true)
    protected String shortName;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Tags")
    protected String tags;
    @XmlElement(name = "Contact")
    protected String contact;
    @XmlElement(name = "Url", required = true)
    protected List<Url> urls;
    @XmlElement(name = "LongName")
    protected String longName;
    @XmlElement(name = "Image")
    protected List<Image> images;
    @XmlElement(name = "Query")
    protected List<Query> queries;
    @XmlElement(name = "Developer")
    protected String developer;
    @XmlElement(name = "Attribution")
    protected String attribution;
    @XmlElement(name = "SyndicationRight", defaultValue = "open")
    protected String syndicationRight;
    @XmlElement(name = "AdultContent")
    protected String adultContent;
    @XmlElement(name = "Language")
    protected List<String> languages;
    @XmlElement(name = "OutputEncoding", defaultValue = "UTF-8")
    protected List<String> outputEncodings;
    @XmlElement(name = "InputEncoding", defaultValue = "UTF-8")
    protected List<String> inputEncodings;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTags(String value) {
        this.tags = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the urls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Url }
     * 
     * 
     */
    public List<Url> getUrls() {
        if (urls == null) {
            urls = new ArrayList<Url>();
        }
        return this.urls;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongName(String value) {
        this.longName = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the images property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     * 
     * 
     */
    public List<Image> getImages() {
        if (images == null) {
            images = new ArrayList<Image>();
        }
        return this.images;
    }

    /**
     * Gets the value of the queries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Query }
     * 
     * 
     */
    public List<Query> getQueries() {
        if (queries == null) {
            queries = new ArrayList<Query>();
        }
        return this.queries;
    }

    /**
     * Gets the value of the developer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * Sets the value of the developer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloper(String value) {
        this.developer = value;
    }

    /**
     * Gets the value of the attribution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * Sets the value of the attribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttribution(String value) {
        this.attribution = value;
    }

    /**
     * Gets the value of the syndicationRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyndicationRight() {
        return syndicationRight;
    }

    /**
     * Sets the value of the syndicationRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyndicationRight(String value) {
        this.syndicationRight = value;
    }

    /**
     * Gets the value of the adultContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdultContent() {
        return adultContent;
    }

    /**
     * Sets the value of the adultContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdultContent(String value) {
        this.adultContent = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguages() {
        if (languages == null) {
            languages = new ArrayList<String>();
        }
        return this.languages;
    }

    /**
     * Gets the value of the outputEncodings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputEncodings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputEncodings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOutputEncodings() {
        if (outputEncodings == null) {
            outputEncodings = new ArrayList<String>();
        }
        return this.outputEncodings;
    }

    /**
     * Gets the value of the inputEncodings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputEncodings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputEncodings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInputEncodings() {
        if (inputEncodings == null) {
            inputEncodings = new ArrayList<String>();
        }
        return this.inputEncodings;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
