//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.19 at 06:15:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://a9.com/-/spec/opensearch/1.1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.a9.opensearch._11;
