//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 08:31:13 PM CET 
//


package ch.so.geo.schema.agi.cadastralinfo._1_0.extract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetExtractByIdResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetExtractByIdResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CadastralExtract" type="{http://geo.so.ch/schema/AGI/CadastralInfo/1.0/Extract}CadastralExtract"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetExtractByIdResponseType", propOrder = {
    "cadastralExtract"
})
@XmlRootElement(name = "GetExtractByIdResponse")
public class GetExtractByIdResponse {

    @XmlElement(name = "CadastralExtract", required = true)
    protected CadastralExtract cadastralExtract;

    /**
     * Gets the value of the cadastralExtract property.
     * 
     * @return
     *     possible object is
     *     {@link CadastralExtract }
     *     
     */
    public CadastralExtract getCadastralExtract() {
        return cadastralExtract;
    }

    /**
     * Sets the value of the cadastralExtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link CadastralExtract }
     *     
     */
    public void setCadastralExtract(CadastralExtract value) {
        this.cadastralExtract = value;
    }

}
