//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.28 at 08:31:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://geo.so.ch/schema/AGI/CadastralInfo/1.0/Extract", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.so.geo.schema.agi.cadastralinfo._1_0.extract;
