//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.22 at 02:52:40 PM CEST 
//


package ch.so.geo.schema.agi.cadastre._0_9.extract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Extract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Extract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="LogoGrundstuecksinformation" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="LogoGrundstuecksinformationRef" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="FederalLogo" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="FederalLogoRef" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CantonalLogo" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="CantonalLogoRef" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element name="MunicipalityLogo" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="MunicipalityLogoRef" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="ResponsibleOffice" type="{http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract}OrganisationType"/&gt;
 *         &lt;element name="RealEstate" type="{http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract}RealEstate_DPR" minOccurs="0"/&gt;
 *         &lt;element name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Extract", propOrder = {
    "logoGrundstuecksinformationRef",
    "logoGrundstuecksinformation",
    "federalLogoRef",
    "federalLogo",
    "cantonalLogoRef",
    "cantonalLogo",
    "municipalityLogoRef",
    "municipalityLogo",
    "responsibleOffice",
    "realEstate",
    "creationDate"
})
public class Extract {

    @XmlElement(name = "LogoGrundstuecksinformationRef")
    @XmlSchemaType(name = "anyURI")
    protected String logoGrundstuecksinformationRef;
    @XmlElement(name = "LogoGrundstuecksinformation")
    protected byte[] logoGrundstuecksinformation;
    @XmlElement(name = "FederalLogoRef")
    @XmlSchemaType(name = "anyURI")
    protected String federalLogoRef;
    @XmlElement(name = "FederalLogo")
    protected byte[] federalLogo;
    @XmlElement(name = "CantonalLogoRef")
    @XmlSchemaType(name = "anyURI")
    protected String cantonalLogoRef;
    @XmlElement(name = "CantonalLogo")
    protected byte[] cantonalLogo;
    @XmlElement(name = "MunicipalityLogoRef")
    @XmlSchemaType(name = "anyURI")
    protected String municipalityLogoRef;
    @XmlElement(name = "MunicipalityLogo")
    protected byte[] municipalityLogo;
    @XmlElement(name = "ResponsibleOffice", required = true)
    protected OrganisationType responsibleOffice;
    @XmlElement(name = "RealEstate")
    protected RealEstateDPR realEstate;
    @XmlElement(name = "CreationDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDate;

    /**
     * Gets the value of the logoGrundstuecksinformationRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoGrundstuecksinformationRef() {
        return logoGrundstuecksinformationRef;
    }

    /**
     * Sets the value of the logoGrundstuecksinformationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoGrundstuecksinformationRef(String value) {
        this.logoGrundstuecksinformationRef = value;
    }

    /**
     * Gets the value of the logoGrundstuecksinformation property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLogoGrundstuecksinformation() {
        return logoGrundstuecksinformation;
    }

    /**
     * Sets the value of the logoGrundstuecksinformation property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLogoGrundstuecksinformation(byte[] value) {
        this.logoGrundstuecksinformation = value;
    }

    /**
     * Gets the value of the federalLogoRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFederalLogoRef() {
        return federalLogoRef;
    }

    /**
     * Sets the value of the federalLogoRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFederalLogoRef(String value) {
        this.federalLogoRef = value;
    }

    /**
     * Gets the value of the federalLogo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFederalLogo() {
        return federalLogo;
    }

    /**
     * Sets the value of the federalLogo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFederalLogo(byte[] value) {
        this.federalLogo = value;
    }

    /**
     * Gets the value of the cantonalLogoRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCantonalLogoRef() {
        return cantonalLogoRef;
    }

    /**
     * Sets the value of the cantonalLogoRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCantonalLogoRef(String value) {
        this.cantonalLogoRef = value;
    }

    /**
     * Gets the value of the cantonalLogo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCantonalLogo() {
        return cantonalLogo;
    }

    /**
     * Sets the value of the cantonalLogo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCantonalLogo(byte[] value) {
        this.cantonalLogo = value;
    }

    /**
     * Gets the value of the municipalityLogoRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipalityLogoRef() {
        return municipalityLogoRef;
    }

    /**
     * Sets the value of the municipalityLogoRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipalityLogoRef(String value) {
        this.municipalityLogoRef = value;
    }

    /**
     * Gets the value of the municipalityLogo property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMunicipalityLogo() {
        return municipalityLogo;
    }

    /**
     * Sets the value of the municipalityLogo property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMunicipalityLogo(byte[] value) {
        this.municipalityLogo = value;
    }

    /**
     * Gets the value of the responsibleOffice property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationType }
     *     
     */
    public OrganisationType getResponsibleOffice() {
        return responsibleOffice;
    }

    /**
     * Sets the value of the responsibleOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationType }
     *     
     */
    public void setResponsibleOffice(OrganisationType value) {
        this.responsibleOffice = value;
    }

    /**
     * Gets the value of the realEstate property.
     * 
     * @return
     *     possible object is
     *     {@link RealEstateDPR }
     *     
     */
    public RealEstateDPR getRealEstate() {
        return realEstate;
    }

    /**
     * Sets the value of the realEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealEstateDPR }
     *     
     */
    public void setRealEstate(RealEstateDPR value) {
        this.realEstate = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

}
