//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.22 at 02:52:40 PM CEST 
//


package ch.so.geo.schema.agi.cadastre._0_9.extract;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetEGRIDResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetEGRIDResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="EGRID" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="IdentND" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="Type" type="{http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract}RealEstateType"/&gt;
 *         &lt;element name="StateOf" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Limit" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="planned" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetEGRIDResponseType", propOrder = {
    "egridsAndPlannedsAndLimits"
})
@XmlRootElement(name = "GetEGRIDResponse")
public class GetEGRIDResponse {

    @XmlElementRefs({
        @XmlElementRef(name = "EGRID", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "planned", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Limit", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StateOf", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Type", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IdentND", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Number", namespace = "http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> egridsAndPlannedsAndLimits;

    /**
     * Gets the value of the egridsAndPlannedsAndLimits property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the egridsAndPlannedsAndLimits property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEGRIDSAndPlannedsAndLimits().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link RealEstateType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getEGRIDSAndPlannedsAndLimits() {
        if (egridsAndPlannedsAndLimits == null) {
            egridsAndPlannedsAndLimits = new ArrayList<JAXBElement<?>>();
        }
        return this.egridsAndPlannedsAndLimits;
    }

}
